name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

      - name: Success Message
        run: echo "Render Deployment Hook Triggered 🚀"